language: python
sudo: true

addons:
  apt:
    packages:
    - docker

install:
  - pip install -r server/requirements.txt
  - cd view; npm install

before_script:
  - cd server; ./manage.py test
  - cd view; npm test

script:
  - echo "$DOCKER_LOGIN vs $DOCKER_PASSWORD"
  - cd view; npm build
  - docker build -t dracks/mrscrooge:test -f config/sqlite/Dockerfile


