language: python
sudo: true

python:
    - "3.6"
node:
    - "8"

cache:
  directories:
    - "view/node_modules"

addons:
  apt:
    packages:
    - docker

install:
  - pip install -r server/requirements.txt
  - cd view; npm install; cd ..

before_script:
  - cd server; ./manage.py test; cd ..
  - cd view; npm test; cd ..

script:
  - echo "$DOCKER_LOGIN vs $DOCKER_PASSWORD"
  - cd view; npm build; cd ..
  - docker build -t dracks/mrscrooge:test -f config/sqlite/Dockerfile

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  - docker push dracks/mrscrooge:test